version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: githubproxy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - githubproxy-net

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: githubproxy-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - githubproxy-net

volumes:
  postgres_data:

networks:
  githubproxy-net:
